### ISSUE TITLE
Can we get scripts which can directly run in shell.

### ISSUE THREAD

**Issue by 444thLiao** [gatk-workflows/gatk4-germline-snps-indels#10]
Just like my title.

I know WDL is a handful tools to use, but actually I use luigi in python to hand on my workflow. 

So Can we get any scripts which can run in shell. That kind of scripts **is the easiest understanding one** in my opinion.

Of course, write another scripts besides WDL is very redundant. 
**Could we get some kind of workflow with special command with parameter?**

Thank you.

**Comment by bshifaw** [comment]
Hi, 
The current focus for this repository are WDLs, it's unlikely we'll be supporting workflows in any other scripts. For info on getting started WDL please use this website: https://software.broadinstitute.org/wdl/documentation/quickstart

Your best bet may be searching bioinformatic forums and websites with the same goals.

Best of Luck.
