### ISSUE TITLE
javaOptions should be changed to java-options in 4.0.0

### ISSUE THREAD

**Issue by sacuba** [gatk-workflows/gatk4-germline-snps-indels#11]
RT

**Comment by sacuba** [comment]
and also :
genomicsDBWorkspace
genomicsdb-workspace-path

batchSize
batch-size

readerThreads
reader-threads

sampleNameMap
sample-name-map'

I wiil pull a request then ,I can not believe that an stable version have such bugs!!!

**Comment by bshifaw** [comment]
Hi,
Originally the wdls were set to use gatk4.beta6 which used camel case in the command arguments. The wdls were updated a few days ago to use gatk4.0.0.0 and included the change from camel case to hyphens like you mentioned. 
Please use the updated wdls.
