### ISSUE TITLE
Cannot find INTERVAL files

### ISSUE THREAD

**Issue by timjeske** [gatk-workflows/gatk4-germline-snps-indels#12]
Dear GATK developers,

I would like to run the germline calling pipeline locally but I can't find where to download the INTERVAL files required for the joint-discovery:

```
  "##_COMMENT3": "INTERVALS",
  "JointGenotyping.eval_interval_list": "gs://broad-references/hg38/v0/wgs_evaluation_regions.hg38.interval_list",
  "JointGenotyping.unpadded_intervals_file": "gs://gatk-test-data/intervals/hg38.even.handcurated.20k.intervals",
```

Can I download them somewhere? Or can I just use the wgs_calling_regions.hg38.interval_list?

Kind regards,
Tim

**Comment by bshifaw** [comment]
All pipeline resources are publicly available and downloadable on google buckets. 
eval_interval_list: https://console.cloud.google.com/storage/browser/broad-references/hg38/v0/
unpadded_intervals_file: https://console.cloud.google.com/storage/browser/gatk-test-data/intervals/

**Comment by timjeske** [comment]
Thanks for your fast answer!
