### ISSUE TITLE
content of the interval file

### ISSUE THREAD

**Issue by thedam** [gatk-workflows/gatk4-germline-snps-indels#17]
Hi,
What is the content of the interval file: gs://gatk-test-data/intervals/hg38_wgs_scattered_calling_intervals.txt ?
Is it just a normal .bed file, or just separated chromosomes?

Cheers

**Comment by bshifaw** [comment]
Please review this gatk article detailing the references and resources (including intervals) used by gatk tools.
https://software.broadinstitute.org/gatk/documentation/article?id=7899
Also, visit the gatk forum to ask the GATK team.
https://gatkforums.broadinstitute.org/gatk/categories/ask-the-team

**Comment by thedam** [comment]
oh, great. GATK's docs are very scattered, I've missed that links :)
thx
