### ISSUE TITLE
Problems with GatherMetrics task

### ISSUE THREAD

**Issue by cwhelan** [gatk-workflows/gatk4-germline-snps-indels#22]
There are several issues with the `GatherMetrics` task in the large cohort code path through `joint-discovery-gatk4.wdl`:

- the `AccumulateVariantCallingMetrics` command prefix is `${gatk_path} --java-option "-Xmx2g -Xms2g" `: should be `--java-options`
- the input to `AccumulateVariantCallingMetrics` is specified as `I=metrics/%s`, but that Picard-style definition is not valid for GATK `AccumulateVariantCallingMetrics`
- `gsutil` is called as `/root/google-cloud-sdk/bin/gsutil` but that path doesn't seem to be valid in the docker I'm using (`gatk:4.0.1.0`)

**Comment by bshifaw** [comment]
PR has been merged and released: https://github.com/gatk-workflows/gatk4-germline-snps-indels/releases/tag/1.0.3
