### ISSUE TITLE
FR: use python:2.7-slim or python:2.7-alpine in joint-discovery-gatk4.wdl

### ISSUE THREAD

**Issue by mbookman** [gatk-workflows/gatk4-germline-snps-indels#27]
The definition for task DynamicallyCombineIntervals uses:

     docker: "python:2.7"

I have run joint-discovery-gatk4.wdl with the `python:2.7-slim` image just fine. I have not tested with the alpine image, but I expect it will work.

Image sizes:

    $ docker images --format "{{.Tag}}\t{{.Size}}" | grep "2.7"
    2.7-alpine    60.1MB
    2.7-slim      120MB
    2.7           908MB

Docker hub performance can sometimes be poor. Pulling smaller images is more reliable.

**Comment by mbookman** [comment]
Note that the joint-discovery-gatk4.hg38.wgs.inputs.json file contains:

    "JointGenotyping.python_docker": "python:2.7",

But the python_docker variable is not used in the WDL.

**Comment by bshifaw** [comment]
@mbookman ,

The tasks in the wdl should be making use of the python docker in the runtime, this will be corrected in the next release. Thanks for bringing it to my attention. 
I'll pass on your suggestion about using the slim down version of python image to the dev team.
