### ISSUE TITLE
JointGenotyping uses a deprecated output syntax

### ISSUE THREAD

**Issue by oneillkza** [gatk-workflows/gatk4-germline-snps-indels#30]
Hi,

I'm trying to wrap Haplotypecaller and Jointgenotyping into a single workflow, and upon running womtool on my wdl, it tells me:

```
Workflow JointGenotyping is used as a sub workflow but has outputs declared with a deprecated syntax not compatible with sub workflows.
To use this workflow as a sub workflow please update the workflow outputs section to the latest WDL specification.
See https://github.com/broadinstitute/wdl/blob/develop/SPEC.md#outputs
```

It's probably a good idea to update to the new syntax.

**Comment by oneillkza** [comment]
Note that someone else has noticed this, and the fix has been sitting in #29 for nearly a month now, waiting to be merged.

**Comment by bshifaw** [comment]
Thanks @oneillkza, edits to the workflow are normally not made directly to the gatk-workflows repos but I'll pass along the pull request to the developers so that this improvement can be added to a future release.

**Comment by oneillkza** [comment]
Thanks @bshifaw !

**Comment by bshifaw** [comment]
merged to master
