### ISSUE TITLE
Exomes

### ISSUE THREAD

**Issue by jeffverboon** [gatk-workflows/gatk4-germline-snps-indels#36]
I would like to test this method to joint call exomes via TERRA/firecloud.  I am unclear what file I should be using for  the two intervals lists.

For eval_interval_list I think "gs://broad-references/hg38/v0/exome_evaluation_regions.v1.interval_list" should be okay as it just looks like hg38 exons.  

Less clear to me is what I should be using for unpadded_intervals_file;  Is this asking for unpadded exon capture regions, or should I just use the gs://.../hg38.even.handcurated.20k.intervals which are used for WGS?

Thanks!

**Comment by bshifaw** [comment]
The unpadded interval file is being used by the workflow to genotype the GVCFs, so the exon capture regions provided by the lab or sequencing provider would be used here.
