### ISSUE TITLE
Wrong docker and path override placeholder in joint-discovery inputs file

### ISSUE THREAD

**Issue by wdesouza** [gatk-workflows/gatk4-germline-snps-indels#37]
I noticed that the commented docker and path override parameters in joint-discovery input file are wrong. They should be `JointGenotyping` instead of `PreProcessingForVariantDiscovery_GATK4`.

- [Docker override](https://github.com/gatk-workflows/gatk4-germline-snps-indels/blob/master/joint-discovery-gatk4-local.hg38.wgs.inputs.json#L41)
- [Path override](https://github.com/gatk-workflows/gatk4-germline-snps-indels/blob/master/joint-discovery-gatk4-local.hg38.wgs.inputs.json#L44)

It also happens in [joint-discovery-gatk4.hg38.wgs.inputs.json](https://github.com/gatk-workflows/gatk4-germline-snps-indels/blob/master/joint-discovery-gatk4.hg38.wgs.inputs.json)

**Comment by bshifaw** [comment]
ahh, thanks.
